import { StyleSheet, Platform, StatusBar } from 'react-native';

const ProductsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight,
    paddingBottom: 16,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  syncTimeText: {
    fontSize: 12,
    color: '#666',
    marginRight: 8,
  },
  syncButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F0F0F0',
  },
  syncButtonDisabled: {
    opacity: 0.7,
  },
  syncButtonText: {
    fontSize: 14,
    color: '#4A90E2',
    fontWeight: '600',
  },
  syncErrorText: {
    fontSize: 12,
    color: '#EF4444',
    fontWeight: '600',
    marginRight: 8,
  },
  searchContainer: {
    padding: 16,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  categoryDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    backgroundColor: '#F5F7FA',
    marginRight: 8,
    minWidth: 180,
  },
  categoryButtonText: {
    fontSize: 14,
    color: '#333',
    marginRight: 4,
  },
  dropdownIcon: {
    fontSize: 12,
    color: '#666',
  },
  viewModeContainer: {
    flexDirection: 'row',
    backgroundColor: '#F5F7FA',
    borderRadius: 8,
    padding: 4,
  },
  viewModeButton: {
    padding: 8,
    borderRadius: 4,
  },
  activeViewMode: {
    backgroundColor: 'white',
  },
  viewModeIcon: {
    fontSize: 20,
    color: '#666',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F7FA',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 40,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  searchIcon: {
    fontSize: 16,
    color: '#999',
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: '#333',
  },
  fullscreenButton: {
    padding: 8,
  },
  fullscreenIcon: {
    fontSize: 18,
    color: '#666',
  },
  filtersContainer: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F5F7FA',
  },
  activeFilter: {
    backgroundColor: '#4A90E2',
  },
  filterText: {
    fontSize: 14,
    color: '#666',
  },
  listContainer: {
    paddingVertical: 16,
  },
  productCard: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  imageColumn: {
    width: 80,
    height: 80,
    marginRight: 16,
  },
  productImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#F5F7FA',
  },
  detailsColumn: {
    flex: 1,
    marginRight: 16,
  },
  productHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  productCode: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginRight: 8,
  },
  starIcon: {
    fontSize: 20,
    color: '#F59E0B',
    marginRight: 8,
  },
  uom: {
    fontSize: 12,
    color: '#666',
    backgroundColor: '#F5F7FA',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  description: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  quantityColumn: {
    width: 80,
    alignItems: 'center',
    marginRight: 16,
  },
  label: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  quantity: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  priceColumn: {
    width: 100,
    alignItems: 'flex-end',
  },
  price: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  discountContainer: {
    alignItems: 'flex-end',
  },
  discountPercentage: {
    fontSize: 12,
    color: '#EF4444',
    fontWeight: '600',
  },
  discountAmount: {
    fontSize: 12,
    color: '#EF4444',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 32,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
  },
  emptyListContainer: {
    flexGrow: 1,
  },
  gridRow: {
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  gridCard: {
    width: '48%',
    backgroundColor: 'white',
    borderRadius: 12,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: 'hidden',
  },
  gridImageContainer: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#F5F7FA',
    padding: 8,
  },
  gridImage: {
    width: '100%',
    height: '100%',
  },
  gridDetails: {
    padding: 12,
  },
  gridHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  gridProductCode: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
  },
  gridDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
    marginBottom: 12,
    height: 54, // Accommodates 3 lines of text
  },
  gridPriceSection: {
    marginBottom: 8,
  },
  gridPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  gridDiscountContainer: {
    marginTop: 2,
  },
  gridDiscountPercentage: {
    fontSize: 12,
    color: '#EF4444',
    fontWeight: '600',
  },
  gridDiscountAmount: {
    fontSize: 12,
    color: '#EF4444',
  },
  gridFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  gridQuantity: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  gridLabel: {
    fontSize: 11,
    color: '#666',
    marginBottom: 2,
  },
  gridQuantityValue: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#333',
  },
  gridUom: {
    fontSize: 11,
    color: '#666',
    backgroundColor: '#F5F7FA',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  activeFiltersContainer: {
    marginTop: 8,
  },
  activeFiltersScroll: {
    flexGrow: 0,
  },
  activeFilterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#EBF8FF',
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#BEE3F8',
  },
  activeFilterText: {
    fontSize: 14,
    color: '#2B6CB0',
    marginRight: 8,
  },
  clearFilterButton: {
    marginLeft: 4,
  },
  clearAllButton: {
    padding: 8,
    borderRadius: 16,
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  clearAllText: {
    fontSize: 14,
    color: '#DC2626',
    fontWeight: '500',
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  checkmark: {
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: '600',
  },
  clearFilterIcon: {
    fontSize: 16,
    color: '#2B6CB0',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  dropdownContainer: {
    marginTop: 100,
    marginHorizontal: 16,
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 8,
    maxHeight: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  dropdownSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: 8,
    marginBottom: 8,
  },
  dropdownSearchInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#F5F7FA',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#333',
  },
  clearSearchButton: {
    padding: 8,
    marginLeft: 8,
  },
  clearSearchIcon: {
    fontSize: 16,
    color: '#666',
  },
  dropdownScrollView: {
    maxHeight: 300,
  },
  selectedDropdownItem: {
    backgroundColor: '#EBF8FF',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#333',
  },
  noResultsContainer: {
    padding: 16,
    alignItems: 'center',
  },
  noResultsText: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
  },
  activeFilterOption: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  qtyFilterContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    margin: 16,
    marginTop: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  qtyFilterHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 12,
    marginBottom: 16,
  },
  qtyFilterTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
  },
  qtyFilterContent: {
    gap: 16,
  },
  qtyFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  qtyFilterLabel: {
    fontSize: 16,
    color: '#4B5563',
    flex: 1,
  },
  criterionButtons: {
    flexDirection: 'row',
    gap: 8,
    flex: 2,
  },
  criterionButton: {
    flex: 1,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
  },
  criterionButtonActive: {
    backgroundColor: '#4A90E2',
    borderColor: '#4A90E2',
  },
  criterionButtonText: {
    fontSize: 18,
    color: '#4B5563',
  },
  criterionButtonTextActive: {
    color: 'white',
  },
  qtyFilterInput: {
    flex: 2,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
  },
  qtyFilterActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 16,
  },
  qtyFilterButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  qtyFilterCancelButton: {
    backgroundColor: '#F3F4F6',
  },
  qtyFilterSubmitButton: {
    backgroundColor: '#4A90E2',
  },
  qtyFilterCancelButtonText: {
    color: '#4B5563',
    fontSize: 16,
    fontWeight: '500',
  },
  qtyFilterSubmitButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  paginationInfo: {
    flex: 1,
  },
  paginationText: {
    fontSize: 14,
    color: '#666',
  },
  paginationControls: {
    flexDirection: 'row',
    gap: 8,
  },
  paginationButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#4A90E2',
  },
  paginationButtonDisabled: {
    backgroundColor: '#E5E7EB',
  },
  paginationButtonText: {
    fontSize: 16,
    color: 'white',
    fontWeight: '600',
  },
  paginationButtonTextDisabled: {
    color: '#999',
  },
  filterIconButton: {
    padding: 8,
    borderRadius: 4,
    position: 'relative',
  },
  filterIcon: {
    fontSize: 18,
    color: '#666',
  },
  filterBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#4A90E2',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    fontSize: 10,
    color: 'white',
    fontWeight: '600',
  },
  filterDropdownContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    margin: 16,
    marginTop: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  filterDropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 12,
    marginBottom: 16,
  },
  filterDropdownTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
  },
  clearAllFiltersText: {
    color: '#4B5563',
    fontSize: 16,
    fontWeight: '500',
  },
  filterDropdownScroll: {
    maxHeight: 300,
  },
  filterSection: {
    marginBottom: 16,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 8,
  },
  filterOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  filterOptionActive: {
    backgroundColor: '#EBF8FF',
  },
  filterOptionText: {
    fontSize: 16,
    color: '#333',
  },
  filterOptionTextActive: {
    fontWeight: '600',
  },
});

export default ProductsScreenStyles; 