import { StyleSheet } from 'react-native';

export const createSessionCardStyles = () => StyleSheet.create({
  sessionCard: {
    backgroundColor: '#f9fafb',
    marginHorizontal: 0,
    marginTop: 0,
    borderRadius: 12,
    padding: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    minHeight: 110,
  },
  sessionInfo: {
    flex: 1,
    marginRight: 12,
  },
  dateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  sessionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sessionDate: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 2,
  },
  sessionTime: {
    fontSize: 15,
    color: '#6b7280',
    marginBottom: 4,
  },
  dayToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 28,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  dayStartButton: {
    backgroundColor: '#22c55e',
  },
  dayEndButton: {
    backgroundColor: '#ef4444',
  },
  dayToggleText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  progressBarContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 6,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#e5e7eb',
  },
  progressBar: {
    height: 6,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    backgroundColor: '#22c55e',
  },
}); 